import json
import pandas as pd
from haversine import haversine
from datetime import date
from pathlib import Path

# loads the training dataset
dataframe = pd.read_csv('../assets/fraudTrain.csv')
# loads the test dataset
dataframe_test = pd.read_csv('../assets/fraudTest.csv')
# a list of columns that will no longer be needed after the necessary information has been extracted including
# the first column which is unnamed
columns_to_remove = [dataframe.columns[0], 'cc_num', 'trans_num', 'unix_time', 'dob', 'trans_date_trans_time', 'lat',
                     'long', 'merch_lat', 'merch_long', 'job']
# jobs are categorised into sectors and the sectors are loaded from a json file
job_sectors = json.load(Path('../misc/job_sector.json').open())


# this extracts the month and hour of transaction from trans_date_trans_time column
def extract_date(data):
    split_data = data.split(" ")
    trans_date = split_data[0]
    time = split_data[1]
    trans_date = trans_date.split("-")[1]
    time = time.split(":")[0]
    return pd.Series([int(trans_date), int(time)])


# this uses the haversine formula to get the distance between the card user and the merchant
# the card was being used at
def calculate_distance(data):
    user_coordinates = (data["lat"], data["long"])
    merch_coordinates = (data["merch_lat"], data["merch_long"])
    distance = haversine(user_coordinates, merch_coordinates, unit='mi')
    return distance


# this extracts the age from the date of birth of the users
def extract_age(data):
    dob = [int(d) for d in data.split("-")]
    difference = date.today() - date(dob[0], dob[1], dob[2])
    return difference.days // 365


# this applies the job sector based on the jobs highlighted in the job column
# it proceeds to apply 'Other' to jobs without a specified sector
def set_job_sector(data):
    try:
        selected_sector = [k for k, v in job_sectors.items() if data in v][0]
    except:
        selected_sector = "Other"
    return selected_sector


# this carries out the cleaning and application of cleaning functions to the dataframes passed through
def clean_dataframe(dataframe_copy):
    # an 'age' column is generated by applying age extracting to the 'dob' column
    dataframe_copy["age"] = dataframe_copy["dob"].apply(extract_age)
    # a 'job_sector' column is generated by setting the job sectors on the 'job' column
    dataframe_copy["job_sector"] = dataframe_copy["job"].apply(set_job_sector)
    # the 'trans_month' and 'trans_hour' columns are formed from the date-time column simultaneously
    dataframe_copy[["trans_month", "trans_hour"]] = dataframe_copy["trans_date_trans_time"].apply(extract_date)
    # the 'trans_distance' column formed by applying the 'calculate_distance' function on the first axis
    # of the dataframe
    dataframe_copy["trans_distance"] = dataframe_copy.apply(calculate_distance, axis=1)
    # the predefined columns to be removed are dropped on the first axis
    dataframe_copy = dataframe_copy.drop(columns_to_remove, axis=1)
    return dataframe_copy


# the cleaned dataframes for both training and testing
dataframe = clean_dataframe(dataframe)
dataframe_test = clean_dataframe(dataframe_test)

# the cleaned dataset is saved to new files with 'index' set to false
# to avoid an unnamed index column in the resulting file
dataframe.to_csv('../assets/cleaned_fraud_train.csv', index=False)
dataframe_test.to_csv('../assets/cleaned_fraud_test.csv', index=False)
